new change

diff --git a/.github/workflows/testRunner.yml b/.github/workflows/testRunner.yml
--- a/.github/workflows/testRunner.yml
+++ b/.github/workflows/testRunner.yml
@@ -44,10 +44,15 @@ jobs:
         run: |
           IFS=',' read -ra BROWSER_LIST <<< "${{ inputs.browsers }}"
           for browser in "${BROWSER_LIST[@]}"; do
-            echo "Running Cypress tests on $browser"
-            REPORT_DIR="cypress/reports/html/$browser"
-            mkdir -p "$REPORT_DIR"
-            npx cypress run --browser "$browser" --spec "${{ inputs.spec_pattern }}" --reporter mochawesome --reporter-options reportDir=$REPORT_DIR,reportFilename=report-$browser.json || echo "Tests failed for $browser, continuing with next browser"
+           echo "Running Cypress tests on $browser"
+           REPORT_DIR="cypress/reports/html/$browser"
+           mkdir -p "$REPORT_DIR"
+           npx cypress run \
+             --browser "$browser" \
+             --spec "${{ inputs.spec_pattern }}" \
+             --reporter mochawesome \
+             --reporter-options reportDir=$REPORT_DIR,overwrite=false,html=false,json=true \
+             || echo "Tests failed for $browser, continuing with next browser"
           done
 
       - name: Merge Reports and Generate HTML
